spring:
  application:
    name: suyo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

management:
  endpoint:
    health:
      probes:
        enabled: true
